name: tetrad
channels: 
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - setuptools
  - loguru
  - toyplot
  - toytree
  - pandas
  - scipy
  - numpy
  - numba
  - ipyparallel >=7
  - typer
