{% set name = "tetrad" %}
{% set version = "0.9.14" %}
{% set sha256 = "797096b4751dd864e2a2371d25bf8d312146250cacc80ec1c25aaee07ef46ba0" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/eaton-lab/tetrad/archive/{{version}}.tar.gz
  sha256: {{sha256}}

# binary relocation is required so cannot do arch.
build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - tetrad = tetrad.__main__:main

# works with mkl or openblas, but mkl is better tested;
# requires conda-forge channel if mpi4py to be included by default...
requirements:
  host:
    - pip
    - python
  run:
    - python
    - scipy             # only used for comb currently; TODO remove.
    - numpy
    - numba >=0.39
    - future
    - h5py
    - toytree >=1.0, <=2.0.5
    - ipyparallel >=6.0.2
    - mpi4py >=3.0

test:
  imports:
    - tetrad
  commands:
    - tetrad -h

about:
  home: http://github.com/eaton-lab/tetrad
  license: GPL3
  license_file: LICENSE
  summary: Quartet tree inference using phylogenetic invariants
