{% set name = "tetrad" %}
{% set version = "0.9.8" %}
{% set sha256 = "afee8d0e7dc9319bff49c830ef926629bb1648c0bdf41bb8039da7cc53f73784" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/eaton-lab/tetrad/archive/{{version}}.tar.gz
  sha256: {{sha256}}

# binary relocation is required so cannot do arch.
build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - tetrad = tetrad.__main__:main

# works with mkl or openblas, but mkl is better tested;
# requires conda-forge channel if mpi4py to be included by default...
requirements:
  host:
    - pip
    - python
  run:
    - python
    - scipy             # only used for comb currently; TODO remove.
    - numpy
    - numba >=0.39
    - future
    - h5py
    - toytree >=0.2
    - ipyparallel >=6.0.2
    - mpi4py >=3.0

test:
  imports:
    - tetrad
  commands:
    - tetrad -h

about:
  home: http://github.com/eaton-lab/tetrad
  license: GPL3
  license_file: LICENSE
  summary: Quartet tree inference using phylogenetic invariants
